### ISSUE TITLE
Support for Django 4.x and Python 3.9/3.10

### ISSUE THREAD

**Issue by schferbe** [thomst/django-more-admin-filters#16] opened 2022-01-05 14:18 UTC
First of all: thank you for providing this nice little lib!

According to the setup.py Django <3.3 and Python up to 3.8 is supported. Are there any plans to support more recent versions of Django and Python? 

What is blocking the support as of today?

**Comment by thomst** [comment] 2023-02-12 21:16
Hi @schferbe .

I now added support for django-4.0 with version 1.4. Unfortunately running tox raises some errors with django-4.1 with specific python versions: Django-4.1 fails with python-3.8 and -3.9. But works with python-3.7 and -3.10. Some debugging about that will be nesseccery.

So try it yourself with Django-4.1 if needed. Hopefully I find some time soon to add official support for 4.1. Best.

**Comment by TTycho** [comment] 2023-03-10 09:28
In the [travis logs](https://app.travis-ci.com/github/thomst/django-more-admin-filters/jobs/591166543) is says ` Service geckodriver unexpectedly exited.`
Is that filter related? What I understand from [SO](https://stackoverflow.com/questions/70821737/webdriverexception-message-service-geckodriver-unexpectedly-exited-status-cod) is that it is a version incompatibility with Selenium.

**Comment by thomst** [comment] 2023-03-13 19:52
@TTycho : This repository do not longer use travis-ci since travis stopped their free support for open-source projects. CI is now running with [github-actions](https://github.com/thomst/django-more-admin-filters/actions/workflows/ci.yml).

**Comment by TTycho** [comment] 2023-03-21 13:27
@thomst , I gave it a try. It took me a bit to figure out how testing works but I was at least able to reproduce the error in 4.1: `Message: Unable to locate element: li a[title="4"]`. But then I got stuck.
When adding data myself, I do see this list item on dropdown_lte3. The filter dropdown_gte3 produces a dropdown when more then three items are inserted and I don't see any difference in this behaviour between 3.2, 4.0 and 4.1. I had some trouble inspecting the test data with `--keepdb` so I can't say if the mock data was added correctly.

Could it be related on how setUpTestData works in 4.1 (see the [release notes](https://docs.djangoproject.com/en/4.1/releases/4.1/))?

**Comment by thomst** [comment] 2023-04-07 13:22
@TTycho  Thank you a lot for trying.

I've now run the tests successfully with django-4.1 and python 3.8, 3.9 and 3.10. I guess the errors came from different dependencies resolving between environments with different python versions. I didn't tracked it down. But I think we should be fine adding 4.1 support now. Thanks for your patience.

**Comment by thomst** [comment] 2023-04-07 13:28
Still not done here. My fault - I forgot to change the version constraint within the setup.py. Which means my tests did use django-4.0 instead of django-4.1. Sorry

**Comment by thomst** [comment] 2023-04-07 14:21
Django-4.1 changed the way filters are rendered. The filters work fine, but the tests not. Unfortunately it is not easy to fix. I would have to completely rewrite some tests to work with 4.1.

**Comment by thomst** [comment] 2023-04-07 20:44
wow. This took me a while. Finally I managed to realise support for django-4.1.

**Closed by thomst** 2023-04-07 20:44 UTC

**Comment by TTycho** [comment] 2023-04-08 10:09
Fantastic! Thanks for looking into this!
